// customize_menu_colour.test.mjs — the menu colour rule: any colour the owner
// picks (or a tint of the accent) is darkened until white menu words reach 7:1.
// The rule lives inside customize_look.js's closure, so its colour block is
// lifted out by its section markers and evaluated on its own. The expected
// hexes are the same ones internal/colour's TestMenuDark pins, so the editor
// preview and the real menu cannot drift apart.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import vm from 'node:vm';

const here = dirname(fileURLToPath(import.meta.url));
const src = readFileSync(join(here, '..', '..', 'static', 'js', 'widgets', 'customize_look.js'), 'utf8');
const start = src.indexOf('/* ---------- Colour');
const end = src.indexOf('/* ---------- Data');
assert.ok(start > 0 && end > start, 'colour block markers not found');

const api = vm.runInNewContext(
  '(function(){ function clamp(v, a, b){ return Math.max(a, Math.min(b, v)); }\n' +
  src.slice(start, end) + '\nreturn { menuDark: menuDark, menuTinted: menuTinted, contrast: contrast }; })()');

// Generated by the JS above; internal/colour/colour_test.go holds the same rows.
const DARK = [
  ['#1a1c23', '#1a1c23'], // Charcoal already passes and is untouched
  ['#0e1424', '#0e1424'],
  ['#2b4a3a', '#2b4a3a'],
  ['#ffffff', null],
  ['#6366f1', null],
  ['#f59e0b', null],
  ['#9a4a26', null],
];
const TINT = ['#6366f1', '#10b981', '#f59e0b', '#06b6d4', '#a855f7', '#ffffff', '#000000'];

test('menuDark leaves a passing colour alone and darkens the rest', () => {
  for (const [input, want] of DARK) {
    const got = api.menuDark(input);
    if (want) assert.equal(got, want, input);
    assert.ok(api.contrast(got, '#ffffff') >= 7, `${input} -> ${got} must reach 7:1`);
  }
});

test('menuDark is case-insensitive and idempotent', () => {
  for (const [input] of DARK) {
    const once = api.menuDark(input);
    assert.equal(api.menuDark(input.toUpperCase()), once);
    assert.equal(api.menuDark(once), once);
  }
});

test('menuTinted always yields a menu white words can sit on', () => {
  for (const accent of TINT) {
    const got = api.menuTinted(accent);
    assert.match(got, /^#[0-9a-f]{6}$/);
    assert.ok(api.contrast(got, '#ffffff') >= 7, `${accent} -> ${got}`);
  }
});

test('pinned values match the Go table', async () => {
  // internal/colour/colour_test.go TestMenuDark / TestMenuTinted hold these.
  const pins = JSON.parse(readFileSync(join(here, 'fixtures', 'menu_colour_pins.json'), 'utf8'));
  for (const [input, want] of Object.entries(pins.dark)) assert.equal(api.menuDark(input), want, 'dark ' + input);
  for (const [input, want] of Object.entries(pins.tinted)) assert.equal(api.menuTinted(input), want, 'tinted ' + input);
});
